name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
        id: vars
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u vulcanize --password-stdin
      - name: Docker build
        run: docker build -t vulcanize/eth-statediff-service:${{ steps.vars.outputs.tag }} https://github.com/vulcanize/eth-statediff-service.git#${{ steps.vars.outputs.tag }}
      - name: Docker push
        run: Dokcer push vulcanize/eth-statediff-service:${{ steps.vars.outputs.tag }}