name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        run: |
        echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "CI_HEAD_REF_SLUG=$CI_HEAD_REF_SLUG"
        echo "CI_HEAD_REF=$CI_HEAD_REF"
        echo "CI_ACTION_REF_NAME=$CI_ACTION_REF_NAME"
        echo "CI_ACTION_REF_NAME_SLUG=$CI_ACTION_REF_NAME_SLUG"
        echo "CI_REF_NAME=$CI_REF_NAME"
        echo "CI_REF_NAME_SLUG=$CI_REF_NAME_SLUG"
        echo "CI_REF=$CI_REF"
        echo "CI_BASE_REF_SLUG=$CI_BASE_REF_SLUG"
        echo "CI_BASE_REF=$CI_BASE_REF"
        echo "CI_WORKFLOW=$CI_WORKFLOW"
        echo "CI_ACTION=$CI_ACTION"
        id: vars
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: tikarya
          password: docker-hub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tikarya/eth-statediff-service:${{ steps.vars.outputs.tag }}
          build-args: |
            BRANCH=$CI_COMMIT_REF_NAME